edited the Readme (is the linked image okay?)
iaacornus/Fedora-OSTree-Setup pull request #49
Opened 2023-02-17 13:36 UTC by trytomakeyouprivate

2023-03-04 04:27 UTC, iaacornus reviewed
i'm not sure about uploading precompiled binary since for users, it can be seen as malicious or just not in a good way. we can just put a script that clones the repo and builds the project, or look if theres an already compiled bin in the repo for it

2023-03-04 04:28 UTC, iaacornus approved these changes

2023-03-04 04:29 UTC, iaacornus requested changes
i think we should not include precompiled binaries, and there are some claims that is quite far from truth

2023-03-07 19:07 UTC, trytomakeyouprivate commented on README.md
> +- no automatic updates for System and Flatpaks, system updates take very long though
Hm that config is small. I havent found the correct systemd .timer yet.

tonywalkers script has a systemd timer with more configs, I  only see here how updates are handled, if they are applied live etc.

I would want configs for
- how often
- at what time
- what time span

2023-03-07 19:10 UTC, trytomakeyouprivate commented
ok removed it, you are right. I mean including it doesnt mean its installed, but I just left if in the readme for now

2023-04-02 02:38 UTC, iaacornus approved these changes

2023-04-02 02:38 UTC, iaacornus commented
you should have a permission over the repo now, since i will be quite busy for a while, but i will join you as soon as possible

2023-04-02 02:39 UTC, merged

2023-04-04 15:14 UTC, trytomakeyouprivate commented on README.md
> +- changing the SDDM theme is not possible, but the standard theme looks very outdated
I will edit that. Quite old, sorry